addEvent(window,"load",sortables_init);var SORT_COLUMN_INDEX;function sortables_init(){if(document.getElementsByTagName){tbls=document.getElementsByTagName("table");for(ti=0;ti<tbls.length;ti++)thisTbl=tbls[ti],thisTbl.id||(thisTbl.id="sortableTable"+this.lastAssignedId++),-1!=(" "+thisTbl.className+" ").indexOf("sortable")&&thisTbl.id&&ts_makeSortable(thisTbl)}}
function ts_makeSortable(a){if(a.rows&&0<a.rows.length)var c=a.rows[0];if(c)for(a=0;a<c.cells.length;a++){var d=c.cells[a],b=ts_getInnerText(d);d.innerHTML='<b><a href="#" class="sortheader" onclick="ts_resortTable(this, '+a+');return false;">'+b+'<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></b>'}}
function ts_getInnerText(a){if("string"==typeof a||"undefined"==typeof a)return a;if(a.innerText)return a.innerText;var c="";a=a.childNodes;for(var d=a.length,b=0;b<d;b++)switch(a[b].nodeType){case 1:c+=ts_getInnerText(a[b]);break;case 3:c+=a[b].nodeValue}return c}
function ts_resortTable(a,c){for(var d,b=0;b<a.childNodes.length;b++)a.childNodes[b].tagName&&"span"==a.childNodes[b].tagName.toLowerCase()&&(d=a.childNodes[b]);ts_getInnerText(d);for(var e=a.parentNode;"td"!=e.nodeName.toLowerCase();)e=e.parentNode;b="undefined"==typeof c?e.cellIndex:c;e=getParent(e,"TABLE");if(!(1>=e.rows.length)){var f=ts_getInnerText(e.rows[1].cells[b]);sortfn=ts_sort_caseinsensitive;f.match(/^\d\d[\/-]\d\d[\/-]\d\d\d\d$/)&&(sortfn=ts_sort_date);f.match(/^\d\d[\/-]\S\S\S[\/-]\d\d\d\d$/)&&
(sortfn=ts_sort_date);f.match(/^\d\d[\/-]\d\d[\/-]\d\d$/)&&(sortfn=ts_sort_date);f.match(/^[\ufffd$]/)&&(sortfn=ts_sort_currency);f.match(/^[\d\.]+\s*(bytes|b|kb|tb|gb|mb)$/i)&&(sortfn=ts_sort_filesize);f.match(/^(Empty|Unlimited)$/)&&(sortfn=ts_sort_filesize);f.match(/^[\d\.]+%?$/)&&(sortfn=ts_sort_numeric);f.match(/^\d+\.\d+\.\d+\.\d+$/)&&(sortfn=ts_sort_ip);SORT_COLUMN_INDEX=b;b=[];for(i=0;i<e.rows[0].length;i++);for(j=1;j<e.rows.length;j++)b[j-1]=e.rows[j];b.sort(sortfn);"down"==d.getAttribute("sortdir")?
(ARROW="&nbsp;&nbsp;&uarr;",b.reverse(),d.setAttribute("sortdir","up")):(ARROW="&nbsp;&nbsp;&darr;",d.setAttribute("sortdir","down"));for(i=0;i<b.length;i++)(!b[i].className||b[i].className&&-1==b[i].className.indexOf("sortbottom"))&&e.tBodies[0].appendChild(b[i]);for(i=0;i<b.length;i++)b[i].className&&-1!=b[i].className.indexOf("sortbottom")&&e.tBodies[0].appendChild(b[i]);e=document.getElementsByTagName("span");for(b=0;b<e.length;b++)"sortarrow"==e[b].className&&getParent(e[b],"table")==getParent(a,
"table")&&(e[b].innerHTML="&nbsp;&nbsp;&nbsp;");d.innerHTML=ARROW}}function getParent(a,c){return null==a?null:1==a.nodeType&&a.tagName.toLowerCase()==c.toLowerCase()?a:getParent(a.parentNode,c)}
function ts_sort_date(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]);bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]);10==aa.length?dt1=aa.substr(6,4)+aa.substr(3,2)+aa.substr(0,2):11==aa.length?dt1=aa.substr(7,4)+ts_month_num(aa.substr(3,3))+aa.substr(0,2):(yr=aa.substr(6,2),yr=50>parseInt(yr)?"20"+yr:"19"+yr,dt1=yr+aa.substr(3,2)+aa.substr(0,2));10==bb.length?dt2=bb.substr(6,4)+bb.substr(3,2)+bb.substr(0,2):11==bb.length?dt2=bb.substr(7,4)+ts_month_num(bb.substr(3,3))+bb.substr(0,2):(yr=bb.substr(6,
2),yr=50>parseInt(yr)?"20"+yr:"19"+yr,dt2=yr+bb.substr(3,2)+bb.substr(0,2));return dt1==dt2?0:dt1<dt2?-1:1}function ts_month_num(a){a=a.toLowerCase();return"jan"==a?"01":"feb"==a?"02":"mar"==a?"03":"apr"==a?"04":"may"==a?"05":"jun"==a?"06":"jul"==a?"07":"aug"==a?"08":"sep"==a?"09":"oct"==a?"10":"nov"==a?"11":"dec"==a?"12":"00"}
function ts_sort_currency(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]).replace(/[^0-9.]/g,"");bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]).replace(/[^0-9.]/g,"");return parseFloat(aa)-parseFloat(bb)}
function ts_sort_filesize(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]).toLowerCase();bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]).toLowerCase();if(0==aa.length)return-1;if(0==bb.length)return 1;var d=/^([\d\.]*|none|empty|unlimited)\s*(bytes|b|kb|tb|gb|mb)?$/i;matchA=aa.match(d);matchB=bb.match(d);"none"==matchA[1]?valA=-999:"empty"==matchA[1]?valA=0:"0"==matchA[1]?valA=0:"unlimited"==matchA[1]?valA=999:"b"==matchA[2]||"bytes"==matchA[2]?valA=1:void 0==matchA[2]||""==matchA[2]?valA=1:"kb"==
matchA[2]?valA=2:"mb"==matchA[2]?valA=3:"gb"==matchA[2]?valA=4:"tb"==matchA[2]&&(valA=5);"none"==matchB[1]?valB=-999:"empty"==matchB[1]?valB=0:"0"==matchB[1]?valB=0:"unlimited"==matchB[1]?valB=999:"b"==matchB[2]||"bytes"==matchB[2]?valB=1:void 0==matchB[2]||""==matchB[2]?valB=1:"kb"==matchB[2]?valB=2:"mb"==matchB[2]?valB=3:"gb"==matchB[2]?valB=4:"tb"==matchB[2]&&(valB=5);if(valA==valB)return isNaN(matchA[1])?-1:isNaN(matchB[1])?1:matchA[1]-matchB[1];if(valA<valB)return-1;if(valA>valB)return 1}
function ts_sort_numeric(a,c){aa=parseFloat(ts_getInnerText(a.cells[SORT_COLUMN_INDEX]));isNaN(aa)&&(aa=0);bb=parseFloat(ts_getInnerText(c.cells[SORT_COLUMN_INDEX]));isNaN(bb)&&(bb=0);return aa-bb}function ts_sort_caseinsensitive(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]).toLowerCase();bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]).toLowerCase();return aa==bb?0:aa<bb?-1:1}
function ts_sort_ip(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]).toLowerCase();bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]).toLowerCase();var d=/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/,b=aa.match(d),d=bb.match(d);return!b?-1:!d?1:parseInt(b[1])<parseInt(d[1])?-1:parseInt(b[1])>parseInt(d[1])?1:parseInt(b[2])<parseInt(d[2])?-1:parseInt(b[2])>parseInt(d[2])?1:parseInt(b[3])<parseInt(d[3])?-1:parseInt(b[3])>parseInt(d[3])?1:parseInt(b[4])<parseInt(d[4])?-1:parseInt(b[4])>parseInt(d[4])?1:0}
function ts_sort_default(a,c){aa=ts_getInnerText(a.cells[SORT_COLUMN_INDEX]);bb=ts_getInnerText(c.cells[SORT_COLUMN_INDEX]);return aa==bb?0:aa<bb?-1:1}function addEvent(a,c,d,b){if(a.addEventListener)return a.addEventListener(c,d,b),!0;if(a.attachEvent)return a.attachEvent("on"+c,d);alert("Handler could not be removed")};
